# Site settings
title: My Code Path
header-img: img/home-bg.jpg
email: itshilei@gmail.com
description: "Talk is cheap, show me your code!"
baseurl: "/blog"
twitter_username: itshilei
github_username:  shic
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: Shi
      